// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NipSearchApp;

#nullable disable

namespace NipSearchApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230709184333_CreateInitial")]
    partial class CreateInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NipSearchApp.Models.AccountNumbers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("subjectId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("subjectId");

                    b.ToTable("AccountNumbers");
                });

            modelBuilder.Entity("NipSearchApp.Models.EntityPerson", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pesel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("subjectId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("EntityPerson");

                    b.HasDiscriminator<string>("Discriminator").HasValue("EntityPerson");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NipSearchApp.Models.Subject", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("hasVirtualAccounts")
                        .HasColumnType("bit");

                    b.Property<string>("krs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pesel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("registrationDenialBasis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("registrationDenialDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("registrationLegalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("regon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("removalBasis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("removalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("residenceAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("restorationBasis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("restorationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("statusVat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("workingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("NipSearchApp.Models.AuthorizedClerks", b =>
                {
                    b.HasBaseType("NipSearchApp.Models.EntityPerson");

                    b.HasIndex("subjectId");

                    b.HasDiscriminator().HasValue("AuthorizedClerks");
                });

            modelBuilder.Entity("NipSearchApp.Models.Partners", b =>
                {
                    b.HasBaseType("NipSearchApp.Models.EntityPerson");

                    b.HasIndex("subjectId");

                    b.HasDiscriminator().HasValue("Partners");
                });

            modelBuilder.Entity("NipSearchApp.Models.Representatives", b =>
                {
                    b.HasBaseType("NipSearchApp.Models.EntityPerson");

                    b.HasIndex("subjectId");

                    b.HasDiscriminator().HasValue("Representatives");
                });

            modelBuilder.Entity("NipSearchApp.Models.AccountNumbers", b =>
                {
                    b.HasOne("NipSearchApp.Models.Subject", "subject")
                        .WithMany("accountNumbers")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("subject");
                });

            modelBuilder.Entity("NipSearchApp.Models.AuthorizedClerks", b =>
                {
                    b.HasOne("NipSearchApp.Models.Subject", "subject")
                        .WithMany("authorizedClerks")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("subject");
                });

            modelBuilder.Entity("NipSearchApp.Models.Partners", b =>
                {
                    b.HasOne("NipSearchApp.Models.Subject", "subject")
                        .WithMany("partners")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("subject");
                });

            modelBuilder.Entity("NipSearchApp.Models.Representatives", b =>
                {
                    b.HasOne("NipSearchApp.Models.Subject", "subject")
                        .WithMany("representatives")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("subject");
                });

            modelBuilder.Entity("NipSearchApp.Models.Subject", b =>
                {
                    b.Navigation("accountNumbers");

                    b.Navigation("authorizedClerks");

                    b.Navigation("partners");

                    b.Navigation("representatives");
                });
#pragma warning restore 612, 618
        }
    }
}
